# Copyright (c) 2021 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.
#
# DON'T EDIT THIS FILE. It was generated by
# /usr/local/lib64/python3.9/site-packages/CTypeGen/__init__.py
# Please see AID/3558 for details on the contents of this file
#
from ctypes import * # pylint: disable=wildcard-import
from CTypeGenRun import * # pylint: disable=wildcard-import
# pylint: disable=unnecessary-pass,protected-access


import Supply


class struct_Demand( Structure, TestableCtypeClass ):
   pass


struct_Demand._ctypegen_native_size = 12
struct_Demand._ctypegen_have_definition = True
struct_Demand._fields_pre = [ # pylint: disable=protected-access
   ( "supplied", Supply.struct_Supply ),
   ( "field2", c_int ),
]
struct_Demand._fields_ = struct_Demand._fields_pre

struct_Demand._ctypegen_offsets = [ 0, 8 ]

Demand = struct_Demand # unambiguous name for tagged type
class Globals(object):
   def __init__(self, dll):
      self.demand = ( struct_Demand ).in_dll( dll, 'demand' )
      pass
def decorateFunctions( lib ):
   pass


CTYPEGEN_producers__ = {
	"GNU C++17 11.2.1 20210728 (Red Hat 11.2.1-1) -mtune=generic -march=x86-64 -g3 -fPIC",
}

if __name__ == "__main__":
   test_classes()
