#!/usr/bin/env python
# Copyright 2020 Arista Networks.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.

import CTypeGen
import argparse

def main():
   ap = argparse.ArgumentParser( description="Generate python from debug info" )
   ap.add_argument( "-i", "--input", metavar="shared library", type=str,
                    nargs='+', help="libraries to process", required=True )
   ap.add_argument( "-o", "--output", metavar="python output", type=str,
                    help="libraries to process", required=True )
   ap.add_argument( "-m", "--modname", metavar="module-name", type=str,
                    help="name for python module", required=False )
   res = ap.parse_args()
   CTypeGen.generateAll( res.input, res.output, modname=res.modname )

if __name__ == "__main__":
   main()
