# Copyright (c) 2018 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.
#
# DON'T EDIT THIS FILE. It was generated by
# /usr/local/lib/python2.7/dist-packages/CTypeGen.py
# Please see AID/3558 for details on the contents of this file
#
from ctypes import * # pylint: disable=wildcard-import
from CTypeGenRun import * # pylint: disable=wildcard-import
# pylint: disable=unnecessary-pass,protected-access




class SomeStructure( Structure, TestableCtypeClass ):
   pass


SomeStructure.native_size = 16
SomeStructure.have_definition = True
SomeStructure._fields_ = [ # pylint: disable=protected-access
   ( "i", c_int ),
   ( "c", c_char ),
   ( "s", c_char_p ),
]

SomeStructure.offsets = [ 0, 4, 8 ]


def decorateFunctions( lib ):
   lib.someFunction.restype = c_double
   lib.someFunction.argtypes = [
      POINTER( SomeStructure ) ]


functionTypes = {
   'someFunction': CFUNCTYPE( c_double, POINTER( SomeStructure )
      ),
}


if __name__ == "__main__":
   test_classes()
